Add Mobile Menu
Munsa1/mobile-menu pull request #1
Opened 2022-04-15 14:24 UTC by Munsa1

# Add Mobile Menu

In the following milestone, I:

- Create a mobile menu
- Add linter config to the codebase
- Folllow git flow

2022-04-15 17:11 UTC, danmainah commented on index.html
> +      <div id="intro">
- [ ] Kindly remove the `<div>` element and replace it with the `<section>` tag, it's a good semantic for SEO and the readability of your page. Please take a look at this [Html Semantic Guide](https://developer.mozilla.org/en-US/docs/Glossary/Semantics)

2022-04-15 17:20 UTC, danmainah requested changes
Hi @Munsa1 ,

2022-04-15 17:26 UTC, danmainah requested changes
Hi @Munsa1 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 🤗 

## Highlights

✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description

# Required Changes ♻️
_Please update your Readme file, use the template given_
_Kindly Ensure the hamburger button is functional_
_Check the comments under the review for more changes requested._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-15 17:26 UTC, danmainah commented on index.html
> +      <div id="contact">
- [ ]  Kindly use a semantic tag like `<section>` instead of `<div>`, this will make your page more readable.

2022-04-15 17:26 UTC, danmainah commented on index.html
> +      <div id="intro">
- [ ] Kindly remove the `<div>` element and replace it with the `<section>` tag, it's a good semantic for SEO and the readability of your page. Please take a look at this [Html Semantic Guide](https://developer.mozilla.org/en-US/docs/Glossary/Semantics)

2022-04-17 12:55 UTC, Munsa1 commented on index.html
> +      <div id="contact">
This section has images only, changing it to a section requires it to have an header tag which is not part of the requirements for the figma template

2022-04-17 13:18 UTC, koomekevo requested changes
Hi @Munsa1, 

<img src="https://media3.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Descriptive Pull Request.
- No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please make sure your README.md is descriptive and professional i.e include 
 - Description.
 - Built with.
 - Authors. 
 - Acknowledment.
 - Licence.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-17 13:18 UTC, koomekevo commented on index.html
> +      <div id="intro">
@Munsa1 Kindly address the suggestion by @danmainah to remove the `<div>` element and replace it with the `<section>` tag.

2022-05-18 09:10 UTC, merged